// @ts-check
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🟢 入门篇 — 基础认知',
      link: {type: 'doc', id: '01-basics/index'},
      items: [
        '01-basics/01-what-is-fde',
        '01-basics/02-learning-path',
        '01-basics/03-fde-types',
      ],
    },
    {
      type: 'category',
      label: '🔵 进阶篇 — 核心技术',
      link: {type: 'doc', id: '02-transformer-basics/transformer-overview'},
      items: [
        '02-transformer-basics/transformer-overview',
        '02-transformer-basics/attention-mechanism',
        '02-transformer-basics/kv-cache',
        '02-transformer-basics/ffn-norm-pos',
        '02-transformer-basics/moe-architecture',
        '03-inference-engines/engine-overview',
        '03-inference-engines/vllm-deep-dive',
        '03-inference-engines/trt-llm-deep-dive',
        '03-inference-engines/sglang-deep-dive',
        '04-quantization/quantization-basics',
        '04-quantization/quantization-schemes',
        '04-quantization/kv-cache-quant',
        '05-gpu-basics/gpu-overview',
        '05-gpu-basics/memory-model',
        '05-gpu-basics/performance-bottleneck',
        '05-gpu-basics/gpu-interconnect',
        '06-distributed/distributed-overview',
        '06-distributed/tensor-parallel',
        '06-distributed/pipeline-parallel',
        '06-distributed/moe-parallel',
      ],
    },
    {
      type: 'category',
      label: '🟠 实战篇 — 生产部署',
      link: {type: 'doc', id: '07-deployment/deployment-architecture'},
      items: [
        '07-deployment/deployment-architecture',
        '07-deployment/kubernetes-deploy',
        '07-deployment/autoscaling',
        '07-deployment/observability',
        '07-deployment/disaster-recovery',
        '07-deployment/multi-tenant',
        '08-cost/cost-breakdown',
        '08-cost/optimization-strategies',
        '08-cost/capacity-planning',
        '08-cost/self-hosted-vs-cloud',
        '09-frontier/frontier-overview',
        '09-frontier/speculative-decoding',
        '09-frontier/fp8-inference',
        '09-frontier/frontier-eval-process',
      ],
    },
    {
      type: 'category',
      label: '🔴 面试篇 — 答题框架',
      link: {type: 'doc', id: '10-interview/interview-framework'},
      items: [
        '10-interview/interview-framework',
        '10-interview/self-intro',
        '10-interview/technical-answers',
        '10-interview/project-stories',
        '10-interview/behavioral',
        '10-interview/hr-round',
        '10-interview/follow-up-qa',
        '10-interview/checklist',
      ],
    },
    {
      type: 'category',
      label: '🟣 管理篇 — 团队建设',
      link: {type: 'doc', id: '11-team-building/index'},
      items: [
        '11-team-building/team-culture',
        '11-team-building/growth-path',
        '11-team-building/training-mechanism',
        '11-team-building/knowledge-management',
        '11-team-building/hiring-strategy',
      ],
    },
  ],
};

module.exports = sidebars;
